version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL-postgresql://flaskuser:flaskpassword@db:5432/flaskdb}
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-flaskuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-flaskpassword}
      POSTGRES_DB: ${POSTGRES_DB:-flaskdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
